[package]
name = "parsey-ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.3"
serde_json = "1.0.108"
tokio = { version = "1.27.0", features = ["full"] }
tonic = "0.10.2"

[build-dependencies]
tonic-build = "0.10.2"
