[package]
name = "parsly-ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.11"
prost = "0.12.3"
serde_json = "1.0.108"
tokio = { version = "1.27.0", features = ["full"] }
tonic = "0.10.2"

[build-dependencies]
tonic-build = "0.10.2"
